version: "3"

tasks:
  kind-create-cluster:
    cmds:
      - kind create cluster --config kind-config.yaml
    desc: Create a Kubernetes cluster using kind

  kind-delete-cluster:
    cmds:
      - kind delete cluster
    desc: Delete a existing kind Kubernetes cluster
