version: "3"

tasks:
  create-namespace:
    desc: "Create a namespace and set as default"
    cmds:
      - kubectl apply -f Namespace.yaml
      - kubens kube-goal-app

  delete-namespace:
    desc: "Delete the namespace to clean up"
    cmds:
      - kubectl delete -f Namespace.yaml

  install-ingress-nginx:
    desc: "Install ingress-nginx"
    cmds:
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - |
        helm upgrade --install \
        ingress-nginx ingress-nginx/ingress-nginx \
        --namespace ingress-nginx \
        --create-namespace

  ingress:apply:
    desc: "Apply ingress for application"
    cmds:
      - kubectl apply -f Ingress.yaml
