apiVersion: apps/v1
kind: Deployment
metadata:
  name:  client-react
  namespace: kube-goal-app
  labels:
    app:  client-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-react
  template:
    metadata:
      labels:
        app:  client-react
    spec:
      containers:
      - image:  dilreni2137/goal-app-client-react:1.0.0
        name:  client-react
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
              cpu: "200m"
              memory: "100Mi"     
        ports:
        - containerPort:  8080
          protocol: TCP
        securityContext:
            allowPrivilegeEscalation: false
            privileged: false
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
        imagePullPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-conf
          name: nginx-conf
      securityContext:
        seccompProfile:
          type: RuntimeDefault