apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configName }}
  namespace: {{ .Values.namespace }}
data:
  default.conf: |-
    server {
      listen 8080;

      location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
          try_files $uri $uri/ /index.html =404;
      }
      
      include /etc/nginx/extra-conf.d/*.conf;
    }
