apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "client-react.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "client-react.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "client-react.labels" . | nindent 8 }}
    spec:
      containers:
      - name:  {{ .Release.Name }}
        image:  "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: 
          {{ .Values.image.pullPolicy }} 
        ports:
        - containerPort:  {{ .Values.service.targetPort }}
          protocol: TCP
        resources: 
          {{- toYaml .Values.resources | nindent 12 }}   
        securityContext: 
          {{- toYaml .Values.securityContext | nindent 12 }}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      securityContext: 
        {{- toYaml .Values.podSecurityContext | nindent 8 }}