service:
  type: ClusterIP
  port: 3000
  targetPort: 8080


namespace: kube-goal-app  

configName: &configNameRef nginx-conf

replicaCount: 1

image:
  repository: dilreni2137/goal-app-client-react
  pullPolicy: Always
  tag: 1.0.0

securityContext: 
  allowPrivilegeEscalation: false
  privileged: false

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: "20m"
    memory: "55M"
  limits:
      cpu: "200m"
      memory: "100Mi" 

volumes:
  - name: *configNameRef
    configMap:
      name: *configNameRef
      defaultMode: 420

volumeMounts:
  - name: *configNameRef
    mountPath: /etc/nginx/conf.d
