apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-fastapi
  namespace: kube-goal-app
  labels:
    app:  api-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-fastapi
  template:
    metadata:
      labels:
        app:  api-fastapi
    spec:
      containers:
      - image:  dilreni2137/goal-app-api-fastapi:1.0.0
        name:  api-fastapi
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
              cpu: "500m"
              memory: "100Mi"
        envFrom:
          - secretRef:
              name: api-fastapi-secret     
        ports:
        - containerPort:  8000
          protocol: TCP 
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        securityContext:
            allowPrivilegeEscalation: false
            privileged: false
        imagePullPolicy: Always
      securityContext:
        seccompProfile:
          type: RuntimeDefault