service:
  type: ClusterIP
  port: 8000



replicaCount: 1

image:
  repository: dilreni2137/goal-app-api-fastapi
  pullPolicy: Always
  tag: 1.0.0

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext: 
  allowPrivilegeEscalation: false
  privileged: false

resources: 
  requests:
    cpu: "20m"
    memory: "55M"
  limits:
      cpu: "500m"
      memory: "100Mi"

livenessProbe:
  httpGet:
    path: /api/health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  
readinessProbe:
  httpGet:
    path: /api/health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2