version: "3"

tasks:
  install-mongodb:
    desc: "Deploy Mongo DB using Helm"
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - |
        helm upgrade --install \
          -n mongodb \
          mongodb bitnami/mongodb \
          --set auth.username=<username> \
          --set auth.password=<password> \
          --set auth.rootPassword=<root_password> \
          --set auth.database=<db_name> \
          --create-namespace
